### ISSUE TITLE
Error "plug-in not found: WiggleIndexerPlugin"

### ISSUE THREAD

**Issue by gedrox** [raoulDoc/WiggleIndexer#2]
Using gradle 2.9, JDK 1.8.0_40. Did "gradle build" and "gradle copyDeps" successfully, but the command

```
$ javac -cp build/libs/WiggleIndexer.jar:"build/libs/*" -Xplugin:WiggleIndexerPlugin samples/Test.java
```

fails with

```
plug-in not found: WiggleIndexerPlugin
```

Checked the `WiggleIndexer.jar` zip and it contains the `WiggleIndexerPlugin` class inside.

**Comment by gedrox** [comment]
This worked for me (Windows):

```
javac -cp "build/libs/*" -Xplugin:WiggleIndexerPlugin samples/Test.java
```

**Comment by raoulDoc** [comment]
Thanks! Please let me know how you progress with java compiler plugins.
